//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * OverFast API
 * OverFast API gives data about Overwatch 2 heroes, gamemodes, maps and players statistics by scraping Blizzard pages. Built with **FastAPI** and **Beautiful Soup**, and uses **nginx** as reverse proxy and **Redis** for caching. By using a Refresh-Ahead cache system, it minimizes calls to Blizzard pages (which can be very slow), and quickly returns accurate data to users.  In players statistics endpoints, several conversions are made for convenience : - all **duration values** are converted into **seconds** (integer) - **percent values** are exposed as **integers** instead of a string with a percent symbol - integer and float string representations are converted into the concerned type  Swagger UI (useful for trying API calls) : https://overfast-api.tekrop.fr/docs
 *
 * The version of the OpenAPI document: 2.17.2
 * Contact: vporchet@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Ana1 } from './Ana1';
import { Ana1FromJSON, Ana1FromJSONTyped, Ana1ToJSON } from './Ana1';
import type { Ashe1 } from './Ashe1';
import { Ashe1FromJSON, Ashe1FromJSONTyped, Ashe1ToJSON } from './Ashe1';
import type { Baptiste1 } from './Baptiste1';
import { Baptiste1FromJSON, Baptiste1FromJSONTyped, Baptiste1ToJSON } from './Baptiste1';
import type { Bastion1 } from './Bastion1';
import { Bastion1FromJSON, Bastion1FromJSONTyped, Bastion1ToJSON } from './Bastion1';
import type { Brigitte1 } from './Brigitte1';
import { Brigitte1FromJSON, Brigitte1FromJSONTyped, Brigitte1ToJSON } from './Brigitte1';
import type { Cassidy1 } from './Cassidy1';
import { Cassidy1FromJSON, Cassidy1FromJSONTyped, Cassidy1ToJSON } from './Cassidy1';
import type { Doomfist1 } from './Doomfist1';
import { Doomfist1FromJSON, Doomfist1FromJSONTyped, Doomfist1ToJSON } from './Doomfist1';
import type { Dva1 } from './Dva1';
import { Dva1FromJSON, Dva1FromJSONTyped, Dva1ToJSON } from './Dva1';
import type { Echo1 } from './Echo1';
import { Echo1FromJSON, Echo1FromJSONTyped, Echo1ToJSON } from './Echo1';
import type { Genji1 } from './Genji1';
import { Genji1FromJSON, Genji1FromJSONTyped, Genji1ToJSON } from './Genji1';
import type { Hanzo1 } from './Hanzo1';
import { Hanzo1FromJSON, Hanzo1FromJSONTyped, Hanzo1ToJSON } from './Hanzo1';
import type { JunkerQueen1 } from './JunkerQueen1';
import { JunkerQueen1FromJSON, JunkerQueen1FromJSONTyped, JunkerQueen1ToJSON } from './JunkerQueen1';
import type { Junkrat1 } from './Junkrat1';
import { Junkrat1FromJSON, Junkrat1FromJSONTyped, Junkrat1ToJSON } from './Junkrat1';
import type { Kiriko1 } from './Kiriko1';
import { Kiriko1FromJSON, Kiriko1FromJSONTyped, Kiriko1ToJSON } from './Kiriko1';
import type { Lifeweaver1 } from './Lifeweaver1';
import { Lifeweaver1FromJSON, Lifeweaver1FromJSONTyped, Lifeweaver1ToJSON } from './Lifeweaver1';
import type { Lucio1 } from './Lucio1';
import { Lucio1FromJSON, Lucio1FromJSONTyped, Lucio1ToJSON } from './Lucio1';
import type { Mei1 } from './Mei1';
import { Mei1FromJSON, Mei1FromJSONTyped, Mei1ToJSON } from './Mei1';
import type { Mercy1 } from './Mercy1';
import { Mercy1FromJSON, Mercy1FromJSONTyped, Mercy1ToJSON } from './Mercy1';
import type { Moira1 } from './Moira1';
import { Moira1FromJSON, Moira1FromJSONTyped, Moira1ToJSON } from './Moira1';
import type { Orisa1 } from './Orisa1';
import { Orisa1FromJSON, Orisa1FromJSONTyped, Orisa1ToJSON } from './Orisa1';
import type { Pharah1 } from './Pharah1';
import { Pharah1FromJSON, Pharah1FromJSONTyped, Pharah1ToJSON } from './Pharah1';
import type { Ramattra1 } from './Ramattra1';
import { Ramattra1FromJSON, Ramattra1FromJSONTyped, Ramattra1ToJSON } from './Ramattra1';
import type { Reaper1 } from './Reaper1';
import { Reaper1FromJSON, Reaper1FromJSONTyped, Reaper1ToJSON } from './Reaper1';
import type { Reinhardt1 } from './Reinhardt1';
import { Reinhardt1FromJSON, Reinhardt1FromJSONTyped, Reinhardt1ToJSON } from './Reinhardt1';
import type { Roadhog1 } from './Roadhog1';
import { Roadhog1FromJSON, Roadhog1FromJSONTyped, Roadhog1ToJSON } from './Roadhog1';
import type { Sigma1 } from './Sigma1';
import { Sigma1FromJSON, Sigma1FromJSONTyped, Sigma1ToJSON } from './Sigma1';
import type { Sojourn1 } from './Sojourn1';
import { Sojourn1FromJSON, Sojourn1FromJSONTyped, Sojourn1ToJSON } from './Sojourn1';
import type { Soldier761 } from './Soldier761';
import { Soldier761FromJSON, Soldier761FromJSONTyped, Soldier761ToJSON } from './Soldier761';
import type { Sombra1 } from './Sombra1';
import { Sombra1FromJSON, Sombra1FromJSONTyped, Sombra1ToJSON } from './Sombra1';
import type { Symmetra1 } from './Symmetra1';
import { Symmetra1FromJSON, Symmetra1FromJSONTyped, Symmetra1ToJSON } from './Symmetra1';
import type { Torbjorn1 } from './Torbjorn1';
import { Torbjorn1FromJSON, Torbjorn1FromJSONTyped, Torbjorn1ToJSON } from './Torbjorn1';
import type { Tracer1 } from './Tracer1';
import { Tracer1FromJSON, Tracer1FromJSONTyped, Tracer1ToJSON } from './Tracer1';
import type { Widowmaker1 } from './Widowmaker1';
import { Widowmaker1FromJSON, Widowmaker1FromJSONTyped, Widowmaker1ToJSON } from './Widowmaker1';
import type { Winston1 } from './Winston1';
import { Winston1FromJSON, Winston1FromJSONTyped, Winston1ToJSON } from './Winston1';
import type { WreckingBall1 } from './WreckingBall1';
import { WreckingBall1FromJSON, WreckingBall1FromJSONTyped, WreckingBall1ToJSON } from './WreckingBall1';
import type { Zarya1 } from './Zarya1';
import { Zarya1FromJSON, Zarya1FromJSONTyped, Zarya1ToJSON } from './Zarya1';
import type { Zenyatta1 } from './Zenyatta1';
import { Zenyatta1FromJSON, Zenyatta1FromJSONTyped, Zenyatta1ToJSON } from './Zenyatta1';

/**
 * Stats of all the heroes played by the player
 * @export
 * @interface Heroes
 */
export interface Heroes {
	/**
	 *
	 * @type {Ana1}
	 * @memberof Heroes
	 */
	ana?: Ana1;
	/**
	 *
	 * @type {Ashe1}
	 * @memberof Heroes
	 */
	ashe?: Ashe1;
	/**
	 *
	 * @type {Baptiste1}
	 * @memberof Heroes
	 */
	baptiste?: Baptiste1;
	/**
	 *
	 * @type {Bastion1}
	 * @memberof Heroes
	 */
	bastion?: Bastion1;
	/**
	 *
	 * @type {Brigitte1}
	 * @memberof Heroes
	 */
	brigitte?: Brigitte1;
	/**
	 *
	 * @type {Cassidy1}
	 * @memberof Heroes
	 */
	cassidy?: Cassidy1;
	/**
	 *
	 * @type {Dva1}
	 * @memberof Heroes
	 */
	dva?: Dva1;
	/**
	 *
	 * @type {Doomfist1}
	 * @memberof Heroes
	 */
	doomfist?: Doomfist1;
	/**
	 *
	 * @type {Echo1}
	 * @memberof Heroes
	 */
	echo?: Echo1;
	/**
	 *
	 * @type {Genji1}
	 * @memberof Heroes
	 */
	genji?: Genji1;
	/**
	 *
	 * @type {Hanzo1}
	 * @memberof Heroes
	 */
	hanzo?: Hanzo1;
	/**
	 *
	 * @type {JunkerQueen1}
	 * @memberof Heroes
	 */
	junkerQueen?: JunkerQueen1;
	/**
	 *
	 * @type {Junkrat1}
	 * @memberof Heroes
	 */
	junkrat?: Junkrat1;
	/**
	 *
	 * @type {Kiriko1}
	 * @memberof Heroes
	 */
	kiriko?: Kiriko1;
	/**
	 *
	 * @type {Lifeweaver1}
	 * @memberof Heroes
	 */
	lifeweaver?: Lifeweaver1;
	/**
	 *
	 * @type {Lucio1}
	 * @memberof Heroes
	 */
	lucio?: Lucio1;
	/**
	 *
	 * @type {Mei1}
	 * @memberof Heroes
	 */
	mei?: Mei1;
	/**
	 *
	 * @type {Mercy1}
	 * @memberof Heroes
	 */
	mercy?: Mercy1;
	/**
	 *
	 * @type {Moira1}
	 * @memberof Heroes
	 */
	moira?: Moira1;
	/**
	 *
	 * @type {Orisa1}
	 * @memberof Heroes
	 */
	orisa?: Orisa1;
	/**
	 *
	 * @type {Pharah1}
	 * @memberof Heroes
	 */
	pharah?: Pharah1;
	/**
	 *
	 * @type {Ramattra1}
	 * @memberof Heroes
	 */
	ramattra?: Ramattra1;
	/**
	 *
	 * @type {Reaper1}
	 * @memberof Heroes
	 */
	reaper?: Reaper1;
	/**
	 *
	 * @type {Reinhardt1}
	 * @memberof Heroes
	 */
	reinhardt?: Reinhardt1;
	/**
	 *
	 * @type {Roadhog1}
	 * @memberof Heroes
	 */
	roadhog?: Roadhog1;
	/**
	 *
	 * @type {Sigma1}
	 * @memberof Heroes
	 */
	sigma?: Sigma1;
	/**
	 *
	 * @type {Sojourn1}
	 * @memberof Heroes
	 */
	sojourn?: Sojourn1;
	/**
	 *
	 * @type {Soldier761}
	 * @memberof Heroes
	 */
	soldier76?: Soldier761;
	/**
	 *
	 * @type {Sombra1}
	 * @memberof Heroes
	 */
	sombra?: Sombra1;
	/**
	 *
	 * @type {Symmetra1}
	 * @memberof Heroes
	 */
	symmetra?: Symmetra1;
	/**
	 *
	 * @type {Torbjorn1}
	 * @memberof Heroes
	 */
	torbjorn?: Torbjorn1;
	/**
	 *
	 * @type {Tracer1}
	 * @memberof Heroes
	 */
	tracer?: Tracer1;
	/**
	 *
	 * @type {Widowmaker1}
	 * @memberof Heroes
	 */
	widowmaker?: Widowmaker1;
	/**
	 *
	 * @type {Winston1}
	 * @memberof Heroes
	 */
	winston?: Winston1;
	/**
	 *
	 * @type {WreckingBall1}
	 * @memberof Heroes
	 */
	wreckingBall?: WreckingBall1;
	/**
	 *
	 * @type {Zarya1}
	 * @memberof Heroes
	 */
	zarya?: Zarya1;
	/**
	 *
	 * @type {Zenyatta1}
	 * @memberof Heroes
	 */
	zenyatta?: Zenyatta1;
}

/**
 * Check if a given object implements the Heroes interface.
 */
export function instanceOfHeroes(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function HeroesFromJSON(json: any): Heroes {
	return HeroesFromJSONTyped(json, false);
}

export function HeroesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Heroes {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		ana: !exists(json, 'ana') ? undefined : Ana1FromJSON(json['ana']),
		ashe: !exists(json, 'ashe') ? undefined : Ashe1FromJSON(json['ashe']),
		baptiste: !exists(json, 'baptiste') ? undefined : Baptiste1FromJSON(json['baptiste']),
		bastion: !exists(json, 'bastion') ? undefined : Bastion1FromJSON(json['bastion']),
		brigitte: !exists(json, 'brigitte') ? undefined : Brigitte1FromJSON(json['brigitte']),
		cassidy: !exists(json, 'cassidy') ? undefined : Cassidy1FromJSON(json['cassidy']),
		dva: !exists(json, 'dva') ? undefined : Dva1FromJSON(json['dva']),
		doomfist: !exists(json, 'doomfist') ? undefined : Doomfist1FromJSON(json['doomfist']),
		echo: !exists(json, 'echo') ? undefined : Echo1FromJSON(json['echo']),
		genji: !exists(json, 'genji') ? undefined : Genji1FromJSON(json['genji']),
		hanzo: !exists(json, 'hanzo') ? undefined : Hanzo1FromJSON(json['hanzo']),
		junkerQueen: !exists(json, 'junker-queen') ? undefined : JunkerQueen1FromJSON(json['junker-queen']),
		junkrat: !exists(json, 'junkrat') ? undefined : Junkrat1FromJSON(json['junkrat']),
		kiriko: !exists(json, 'kiriko') ? undefined : Kiriko1FromJSON(json['kiriko']),
		lifeweaver: !exists(json, 'lifeweaver') ? undefined : Lifeweaver1FromJSON(json['lifeweaver']),
		lucio: !exists(json, 'lucio') ? undefined : Lucio1FromJSON(json['lucio']),
		mei: !exists(json, 'mei') ? undefined : Mei1FromJSON(json['mei']),
		mercy: !exists(json, 'mercy') ? undefined : Mercy1FromJSON(json['mercy']),
		moira: !exists(json, 'moira') ? undefined : Moira1FromJSON(json['moira']),
		orisa: !exists(json, 'orisa') ? undefined : Orisa1FromJSON(json['orisa']),
		pharah: !exists(json, 'pharah') ? undefined : Pharah1FromJSON(json['pharah']),
		ramattra: !exists(json, 'ramattra') ? undefined : Ramattra1FromJSON(json['ramattra']),
		reaper: !exists(json, 'reaper') ? undefined : Reaper1FromJSON(json['reaper']),
		reinhardt: !exists(json, 'reinhardt') ? undefined : Reinhardt1FromJSON(json['reinhardt']),
		roadhog: !exists(json, 'roadhog') ? undefined : Roadhog1FromJSON(json['roadhog']),
		sigma: !exists(json, 'sigma') ? undefined : Sigma1FromJSON(json['sigma']),
		sojourn: !exists(json, 'sojourn') ? undefined : Sojourn1FromJSON(json['sojourn']),
		soldier76: !exists(json, 'soldier-76') ? undefined : Soldier761FromJSON(json['soldier-76']),
		sombra: !exists(json, 'sombra') ? undefined : Sombra1FromJSON(json['sombra']),
		symmetra: !exists(json, 'symmetra') ? undefined : Symmetra1FromJSON(json['symmetra']),
		torbjorn: !exists(json, 'torbjorn') ? undefined : Torbjorn1FromJSON(json['torbjorn']),
		tracer: !exists(json, 'tracer') ? undefined : Tracer1FromJSON(json['tracer']),
		widowmaker: !exists(json, 'widowmaker') ? undefined : Widowmaker1FromJSON(json['widowmaker']),
		winston: !exists(json, 'winston') ? undefined : Winston1FromJSON(json['winston']),
		wreckingBall: !exists(json, 'wrecking-ball') ? undefined : WreckingBall1FromJSON(json['wrecking-ball']),
		zarya: !exists(json, 'zarya') ? undefined : Zarya1FromJSON(json['zarya']),
		zenyatta: !exists(json, 'zenyatta') ? undefined : Zenyatta1FromJSON(json['zenyatta'])
	};
}

export function HeroesToJSON(value?: Heroes | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		ana: Ana1ToJSON(value.ana),
		ashe: Ashe1ToJSON(value.ashe),
		baptiste: Baptiste1ToJSON(value.baptiste),
		bastion: Bastion1ToJSON(value.bastion),
		brigitte: Brigitte1ToJSON(value.brigitte),
		cassidy: Cassidy1ToJSON(value.cassidy),
		dva: Dva1ToJSON(value.dva),
		doomfist: Doomfist1ToJSON(value.doomfist),
		echo: Echo1ToJSON(value.echo),
		genji: Genji1ToJSON(value.genji),
		hanzo: Hanzo1ToJSON(value.hanzo),
		'junker-queen': JunkerQueen1ToJSON(value.junkerQueen),
		junkrat: Junkrat1ToJSON(value.junkrat),
		kiriko: Kiriko1ToJSON(value.kiriko),
		lifeweaver: Lifeweaver1ToJSON(value.lifeweaver),
		lucio: Lucio1ToJSON(value.lucio),
		mei: Mei1ToJSON(value.mei),
		mercy: Mercy1ToJSON(value.mercy),
		moira: Moira1ToJSON(value.moira),
		orisa: Orisa1ToJSON(value.orisa),
		pharah: Pharah1ToJSON(value.pharah),
		ramattra: Ramattra1ToJSON(value.ramattra),
		reaper: Reaper1ToJSON(value.reaper),
		reinhardt: Reinhardt1ToJSON(value.reinhardt),
		roadhog: Roadhog1ToJSON(value.roadhog),
		sigma: Sigma1ToJSON(value.sigma),
		sojourn: Sojourn1ToJSON(value.sojourn),
		'soldier-76': Soldier761ToJSON(value.soldier76),
		sombra: Sombra1ToJSON(value.sombra),
		symmetra: Symmetra1ToJSON(value.symmetra),
		torbjorn: Torbjorn1ToJSON(value.torbjorn),
		tracer: Tracer1ToJSON(value.tracer),
		widowmaker: Widowmaker1ToJSON(value.widowmaker),
		winston: Winston1ToJSON(value.winston),
		'wrecking-ball': WreckingBall1ToJSON(value.wreckingBall),
		zarya: Zarya1ToJSON(value.zarya),
		zenyatta: Zenyatta1ToJSON(value.zenyatta)
	};
}
