//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * OverFast API
 * OverFast API gives data about Overwatch 2 heroes, gamemodes, maps and players statistics by scraping Blizzard pages. Built with **FastAPI** and **Beautiful Soup**, and uses **nginx** as reverse proxy and **Redis** for caching. By using a Refresh-Ahead cache system, it minimizes calls to Blizzard pages (which can be very slow), and quickly returns accurate data to users.  In players statistics endpoints, several conversions are made for convenience : - all **duration values** are converted into **seconds** (integer) - **percent values** are exposed as **integers** instead of a string with a percent symbol - integer and float string representations are converted into the concerned type  Swagger UI (useful for trying API calls) : https://overfast-api.tekrop.fr/docs
 *
 * The version of the OpenAPI document: 2.17.2
 * Contact: vporchet@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HeroKey } from './HeroKey';
import { HeroKeyFromJSON, HeroKeyFromJSONTyped, HeroKeyToJSON } from './HeroKey';
import type { Role } from './Role';
import { RoleFromJSON, RoleFromJSONTyped, RoleToJSON } from './Role';

/**
 *
 * @export
 * @interface HeroShort
 */
export interface HeroShort {
	/**
	 *
	 * @type {HeroKey}
	 * @memberof HeroShort
	 */
	key: HeroKey;
	/**
	 * Name of the hero
	 * @type {string}
	 * @memberof HeroShort
	 */
	name: string;
	/**
	 * Portrait picture URL of the hero
	 * @type {string}
	 * @memberof HeroShort
	 */
	portrait: string;
	/**
	 *
	 * @type {Role}
	 * @memberof HeroShort
	 */
	role: Role;
}

/**
 * Check if a given object implements the HeroShort interface.
 */
export function instanceOfHeroShort(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'key' in value;
	isInstance = isInstance && 'name' in value;
	isInstance = isInstance && 'portrait' in value;
	isInstance = isInstance && 'role' in value;

	return isInstance;
}

export function HeroShortFromJSON(json: any): HeroShort {
	return HeroShortFromJSONTyped(json, false);
}

export function HeroShortFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeroShort {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		key: HeroKeyFromJSON(json['key']),
		name: json['name'],
		portrait: json['portrait'],
		role: RoleFromJSON(json['role'])
	};
}

export function HeroShortToJSON(value?: HeroShort | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		key: HeroKeyToJSON(value.key),
		name: value.name,
		portrait: value.portrait,
		role: RoleToJSON(value.role)
	};
}
