//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * OverFast API
 * OverFast API gives data about Overwatch 2 heroes, gamemodes, maps and players statistics by scraping Blizzard pages. Built with **FastAPI** and **Beautiful Soup**, and uses **nginx** as reverse proxy and **Redis** for caching. By using a Refresh-Ahead cache system, it minimizes calls to Blizzard pages (which can be very slow), and quickly returns accurate data to users.  In players statistics endpoints, several conversions are made for convenience : - all **duration values** are converted into **seconds** (integer) - **percent values** are exposed as **integers** instead of a string with a percent symbol - integer and float string representations are converted into the concerned type  Swagger UI (useful for trying API calls) : https://overfast-api.tekrop.fr/docs
 *
 * The version of the OpenAPI document: 2.17.2
 * Contact: vporchet@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CareerStatCategory } from './CareerStatCategory';
import { CareerStatCategoryFromJSON, CareerStatCategoryFromJSONTyped, CareerStatCategoryToJSON } from './CareerStatCategory';
import type { SingleCareerStat } from './SingleCareerStat';
import { SingleCareerStatFromJSON, SingleCareerStatFromJSONTyped, SingleCareerStatToJSON } from './SingleCareerStat';

/**
 *
 * @export
 * @interface HeroCareerStats
 */
export interface HeroCareerStats {
	/**
	 *
	 * @type {CareerStatCategory}
	 * @memberof HeroCareerStats
	 */
	category: CareerStatCategory;
	/**
	 * Label of the stat category
	 * @type {string}
	 * @memberof HeroCareerStats
	 */
	label: string;
	/**
	 * List of statistics associated with the category
	 * @type {Array<SingleCareerStat>}
	 * @memberof HeroCareerStats
	 */
	stats: Array<SingleCareerStat>;
}

/**
 * Check if a given object implements the HeroCareerStats interface.
 */
export function instanceOfHeroCareerStats(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'category' in value;
	isInstance = isInstance && 'label' in value;
	isInstance = isInstance && 'stats' in value;

	return isInstance;
}

export function HeroCareerStatsFromJSON(json: any): HeroCareerStats {
	return HeroCareerStatsFromJSONTyped(json, false);
}

export function HeroCareerStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeroCareerStats {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		category: CareerStatCategoryFromJSON(json['category']),
		label: json['label'],
		stats: (json['stats'] as Array<any>).map(SingleCareerStatFromJSON)
	};
}

export function HeroCareerStatsToJSON(value?: HeroCareerStats | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		category: CareerStatCategoryToJSON(value.category),
		label: value.label,
		stats: (value.stats as Array<any>).map(SingleCareerStatToJSON)
	};
}
