//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * OverFast API
 * OverFast API gives data about Overwatch 2 heroes, gamemodes, maps and players statistics by scraping Blizzard pages. Built with **FastAPI** and **Beautiful Soup**, and uses **nginx** as reverse proxy and **Redis** for caching. By using a Refresh-Ahead cache system, it minimizes calls to Blizzard pages (which can be very slow), and quickly returns accurate data to users.  In players statistics endpoints, several conversions are made for convenience : - all **duration values** are converted into **seconds** (integer) - **percent values** are exposed as **integers** instead of a string with a percent symbol - integer and float string representations are converted into the concerned type  Swagger UI (useful for trying API calls) : https://overfast-api.tekrop.fr/docs
 *
 * The version of the OpenAPI document: 2.17.2
 * Contact: vporchet@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AllHeroes } from './AllHeroes';
import { AllHeroesFromJSON, AllHeroesFromJSONTyped, AllHeroesToJSON } from './AllHeroes';
import type { Ana } from './Ana';
import { AnaFromJSON, AnaFromJSONTyped, AnaToJSON } from './Ana';
import type { Ashe } from './Ashe';
import { AsheFromJSON, AsheFromJSONTyped, AsheToJSON } from './Ashe';
import type { Baptiste } from './Baptiste';
import { BaptisteFromJSON, BaptisteFromJSONTyped, BaptisteToJSON } from './Baptiste';
import type { Bastion } from './Bastion';
import { BastionFromJSON, BastionFromJSONTyped, BastionToJSON } from './Bastion';
import type { Brigitte } from './Brigitte';
import { BrigitteFromJSON, BrigitteFromJSONTyped, BrigitteToJSON } from './Brigitte';
import type { Cassidy } from './Cassidy';
import { CassidyFromJSON, CassidyFromJSONTyped, CassidyToJSON } from './Cassidy';
import type { Doomfist } from './Doomfist';
import { DoomfistFromJSON, DoomfistFromJSONTyped, DoomfistToJSON } from './Doomfist';
import type { Dva } from './Dva';
import { DvaFromJSON, DvaFromJSONTyped, DvaToJSON } from './Dva';
import type { Echo } from './Echo';
import { EchoFromJSON, EchoFromJSONTyped, EchoToJSON } from './Echo';
import type { Genji } from './Genji';
import { GenjiFromJSON, GenjiFromJSONTyped, GenjiToJSON } from './Genji';
import type { Hanzo } from './Hanzo';
import { HanzoFromJSON, HanzoFromJSONTyped, HanzoToJSON } from './Hanzo';
import type { JunkerQueen } from './JunkerQueen';
import { JunkerQueenFromJSON, JunkerQueenFromJSONTyped, JunkerQueenToJSON } from './JunkerQueen';
import type { Junkrat } from './Junkrat';
import { JunkratFromJSON, JunkratFromJSONTyped, JunkratToJSON } from './Junkrat';
import type { Kiriko } from './Kiriko';
import { KirikoFromJSON, KirikoFromJSONTyped, KirikoToJSON } from './Kiriko';
import type { Lifeweaver } from './Lifeweaver';
import { LifeweaverFromJSON, LifeweaverFromJSONTyped, LifeweaverToJSON } from './Lifeweaver';
import type { Lucio } from './Lucio';
import { LucioFromJSON, LucioFromJSONTyped, LucioToJSON } from './Lucio';
import type { Mei } from './Mei';
import { MeiFromJSON, MeiFromJSONTyped, MeiToJSON } from './Mei';
import type { Mercy } from './Mercy';
import { MercyFromJSON, MercyFromJSONTyped, MercyToJSON } from './Mercy';
import type { Moira } from './Moira';
import { MoiraFromJSON, MoiraFromJSONTyped, MoiraToJSON } from './Moira';
import type { Orisa } from './Orisa';
import { OrisaFromJSON, OrisaFromJSONTyped, OrisaToJSON } from './Orisa';
import type { Pharah } from './Pharah';
import { PharahFromJSON, PharahFromJSONTyped, PharahToJSON } from './Pharah';
import type { Ramattra } from './Ramattra';
import { RamattraFromJSON, RamattraFromJSONTyped, RamattraToJSON } from './Ramattra';
import type { Reaper } from './Reaper';
import { ReaperFromJSON, ReaperFromJSONTyped, ReaperToJSON } from './Reaper';
import type { Reinhardt } from './Reinhardt';
import { ReinhardtFromJSON, ReinhardtFromJSONTyped, ReinhardtToJSON } from './Reinhardt';
import type { Roadhog } from './Roadhog';
import { RoadhogFromJSON, RoadhogFromJSONTyped, RoadhogToJSON } from './Roadhog';
import type { Sigma } from './Sigma';
import { SigmaFromJSON, SigmaFromJSONTyped, SigmaToJSON } from './Sigma';
import type { Sojourn } from './Sojourn';
import { SojournFromJSON, SojournFromJSONTyped, SojournToJSON } from './Sojourn';
import type { Soldier76 } from './Soldier76';
import { Soldier76FromJSON, Soldier76FromJSONTyped, Soldier76ToJSON } from './Soldier76';
import type { Sombra } from './Sombra';
import { SombraFromJSON, SombraFromJSONTyped, SombraToJSON } from './Sombra';
import type { Symmetra } from './Symmetra';
import { SymmetraFromJSON, SymmetraFromJSONTyped, SymmetraToJSON } from './Symmetra';
import type { Torbjorn } from './Torbjorn';
import { TorbjornFromJSON, TorbjornFromJSONTyped, TorbjornToJSON } from './Torbjorn';
import type { Tracer } from './Tracer';
import { TracerFromJSON, TracerFromJSONTyped, TracerToJSON } from './Tracer';
import type { Widowmaker } from './Widowmaker';
import { WidowmakerFromJSON, WidowmakerFromJSONTyped, WidowmakerToJSON } from './Widowmaker';
import type { Winston } from './Winston';
import { WinstonFromJSON, WinstonFromJSONTyped, WinstonToJSON } from './Winston';
import type { WreckingBall } from './WreckingBall';
import { WreckingBallFromJSON, WreckingBallFromJSONTyped, WreckingBallToJSON } from './WreckingBall';
import type { Zarya } from './Zarya';
import { ZaryaFromJSON, ZaryaFromJSONTyped, ZaryaToJSON } from './Zarya';
import type { Zenyatta } from './Zenyatta';
import { ZenyattaFromJSON, ZenyattaFromJSONTyped, ZenyattaToJSON } from './Zenyatta';

/**
 *
 * @export
 * @interface PlayerCareerStats
 */
export interface PlayerCareerStats {
	/**
	 *
	 * @type {AllHeroes}
	 * @memberof PlayerCareerStats
	 */
	allHeroes?: AllHeroes;
	/**
	 *
	 * @type {Ana}
	 * @memberof PlayerCareerStats
	 */
	ana?: Ana;
	/**
	 *
	 * @type {Ashe}
	 * @memberof PlayerCareerStats
	 */
	ashe?: Ashe;
	/**
	 *
	 * @type {Baptiste}
	 * @memberof PlayerCareerStats
	 */
	baptiste?: Baptiste;
	/**
	 *
	 * @type {Bastion}
	 * @memberof PlayerCareerStats
	 */
	bastion?: Bastion;
	/**
	 *
	 * @type {Brigitte}
	 * @memberof PlayerCareerStats
	 */
	brigitte?: Brigitte;
	/**
	 *
	 * @type {Cassidy}
	 * @memberof PlayerCareerStats
	 */
	cassidy?: Cassidy;
	/**
	 *
	 * @type {Dva}
	 * @memberof PlayerCareerStats
	 */
	dva?: Dva;
	/**
	 *
	 * @type {Doomfist}
	 * @memberof PlayerCareerStats
	 */
	doomfist?: Doomfist;
	/**
	 *
	 * @type {Echo}
	 * @memberof PlayerCareerStats
	 */
	echo?: Echo;
	/**
	 *
	 * @type {Genji}
	 * @memberof PlayerCareerStats
	 */
	genji?: Genji;
	/**
	 *
	 * @type {Hanzo}
	 * @memberof PlayerCareerStats
	 */
	hanzo?: Hanzo;
	/**
	 *
	 * @type {JunkerQueen}
	 * @memberof PlayerCareerStats
	 */
	junkerQueen?: JunkerQueen;
	/**
	 *
	 * @type {Junkrat}
	 * @memberof PlayerCareerStats
	 */
	junkrat?: Junkrat;
	/**
	 *
	 * @type {Kiriko}
	 * @memberof PlayerCareerStats
	 */
	kiriko?: Kiriko;
	/**
	 *
	 * @type {Lifeweaver}
	 * @memberof PlayerCareerStats
	 */
	lifeweaver?: Lifeweaver;
	/**
	 *
	 * @type {Lucio}
	 * @memberof PlayerCareerStats
	 */
	lucio?: Lucio;
	/**
	 *
	 * @type {Mei}
	 * @memberof PlayerCareerStats
	 */
	mei?: Mei;
	/**
	 *
	 * @type {Mercy}
	 * @memberof PlayerCareerStats
	 */
	mercy?: Mercy;
	/**
	 *
	 * @type {Moira}
	 * @memberof PlayerCareerStats
	 */
	moira?: Moira;
	/**
	 *
	 * @type {Orisa}
	 * @memberof PlayerCareerStats
	 */
	orisa?: Orisa;
	/**
	 *
	 * @type {Pharah}
	 * @memberof PlayerCareerStats
	 */
	pharah?: Pharah;
	/**
	 *
	 * @type {Ramattra}
	 * @memberof PlayerCareerStats
	 */
	ramattra?: Ramattra;
	/**
	 *
	 * @type {Reaper}
	 * @memberof PlayerCareerStats
	 */
	reaper?: Reaper;
	/**
	 *
	 * @type {Reinhardt}
	 * @memberof PlayerCareerStats
	 */
	reinhardt?: Reinhardt;
	/**
	 *
	 * @type {Roadhog}
	 * @memberof PlayerCareerStats
	 */
	roadhog?: Roadhog;
	/**
	 *
	 * @type {Sigma}
	 * @memberof PlayerCareerStats
	 */
	sigma?: Sigma;
	/**
	 *
	 * @type {Sojourn}
	 * @memberof PlayerCareerStats
	 */
	sojourn?: Sojourn;
	/**
	 *
	 * @type {Soldier76}
	 * @memberof PlayerCareerStats
	 */
	soldier76?: Soldier76;
	/**
	 *
	 * @type {Sombra}
	 * @memberof PlayerCareerStats
	 */
	sombra?: Sombra;
	/**
	 *
	 * @type {Symmetra}
	 * @memberof PlayerCareerStats
	 */
	symmetra?: Symmetra;
	/**
	 *
	 * @type {Torbjorn}
	 * @memberof PlayerCareerStats
	 */
	torbjorn?: Torbjorn;
	/**
	 *
	 * @type {Tracer}
	 * @memberof PlayerCareerStats
	 */
	tracer?: Tracer;
	/**
	 *
	 * @type {Widowmaker}
	 * @memberof PlayerCareerStats
	 */
	widowmaker?: Widowmaker;
	/**
	 *
	 * @type {Winston}
	 * @memberof PlayerCareerStats
	 */
	winston?: Winston;
	/**
	 *
	 * @type {WreckingBall}
	 * @memberof PlayerCareerStats
	 */
	wreckingBall?: WreckingBall;
	/**
	 *
	 * @type {Zarya}
	 * @memberof PlayerCareerStats
	 */
	zarya?: Zarya;
	/**
	 *
	 * @type {Zenyatta}
	 * @memberof PlayerCareerStats
	 */
	zenyatta?: Zenyatta;
}

/**
 * Check if a given object implements the PlayerCareerStats interface.
 */
export function instanceOfPlayerCareerStats(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function PlayerCareerStatsFromJSON(json: any): PlayerCareerStats {
	return PlayerCareerStatsFromJSONTyped(json, false);
}

export function PlayerCareerStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerCareerStats {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		allHeroes: !exists(json, 'all-heroes') ? undefined : AllHeroesFromJSON(json['all-heroes']),
		ana: !exists(json, 'ana') ? undefined : AnaFromJSON(json['ana']),
		ashe: !exists(json, 'ashe') ? undefined : AsheFromJSON(json['ashe']),
		baptiste: !exists(json, 'baptiste') ? undefined : BaptisteFromJSON(json['baptiste']),
		bastion: !exists(json, 'bastion') ? undefined : BastionFromJSON(json['bastion']),
		brigitte: !exists(json, 'brigitte') ? undefined : BrigitteFromJSON(json['brigitte']),
		cassidy: !exists(json, 'cassidy') ? undefined : CassidyFromJSON(json['cassidy']),
		dva: !exists(json, 'dva') ? undefined : DvaFromJSON(json['dva']),
		doomfist: !exists(json, 'doomfist') ? undefined : DoomfistFromJSON(json['doomfist']),
		echo: !exists(json, 'echo') ? undefined : EchoFromJSON(json['echo']),
		genji: !exists(json, 'genji') ? undefined : GenjiFromJSON(json['genji']),
		hanzo: !exists(json, 'hanzo') ? undefined : HanzoFromJSON(json['hanzo']),
		junkerQueen: !exists(json, 'junker-queen') ? undefined : JunkerQueenFromJSON(json['junker-queen']),
		junkrat: !exists(json, 'junkrat') ? undefined : JunkratFromJSON(json['junkrat']),
		kiriko: !exists(json, 'kiriko') ? undefined : KirikoFromJSON(json['kiriko']),
		lifeweaver: !exists(json, 'lifeweaver') ? undefined : LifeweaverFromJSON(json['lifeweaver']),
		lucio: !exists(json, 'lucio') ? undefined : LucioFromJSON(json['lucio']),
		mei: !exists(json, 'mei') ? undefined : MeiFromJSON(json['mei']),
		mercy: !exists(json, 'mercy') ? undefined : MercyFromJSON(json['mercy']),
		moira: !exists(json, 'moira') ? undefined : MoiraFromJSON(json['moira']),
		orisa: !exists(json, 'orisa') ? undefined : OrisaFromJSON(json['orisa']),
		pharah: !exists(json, 'pharah') ? undefined : PharahFromJSON(json['pharah']),
		ramattra: !exists(json, 'ramattra') ? undefined : RamattraFromJSON(json['ramattra']),
		reaper: !exists(json, 'reaper') ? undefined : ReaperFromJSON(json['reaper']),
		reinhardt: !exists(json, 'reinhardt') ? undefined : ReinhardtFromJSON(json['reinhardt']),
		roadhog: !exists(json, 'roadhog') ? undefined : RoadhogFromJSON(json['roadhog']),
		sigma: !exists(json, 'sigma') ? undefined : SigmaFromJSON(json['sigma']),
		sojourn: !exists(json, 'sojourn') ? undefined : SojournFromJSON(json['sojourn']),
		soldier76: !exists(json, 'soldier-76') ? undefined : Soldier76FromJSON(json['soldier-76']),
		sombra: !exists(json, 'sombra') ? undefined : SombraFromJSON(json['sombra']),
		symmetra: !exists(json, 'symmetra') ? undefined : SymmetraFromJSON(json['symmetra']),
		torbjorn: !exists(json, 'torbjorn') ? undefined : TorbjornFromJSON(json['torbjorn']),
		tracer: !exists(json, 'tracer') ? undefined : TracerFromJSON(json['tracer']),
		widowmaker: !exists(json, 'widowmaker') ? undefined : WidowmakerFromJSON(json['widowmaker']),
		winston: !exists(json, 'winston') ? undefined : WinstonFromJSON(json['winston']),
		wreckingBall: !exists(json, 'wrecking-ball') ? undefined : WreckingBallFromJSON(json['wrecking-ball']),
		zarya: !exists(json, 'zarya') ? undefined : ZaryaFromJSON(json['zarya']),
		zenyatta: !exists(json, 'zenyatta') ? undefined : ZenyattaFromJSON(json['zenyatta'])
	};
}

export function PlayerCareerStatsToJSON(value?: PlayerCareerStats | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		'all-heroes': AllHeroesToJSON(value.allHeroes),
		ana: AnaToJSON(value.ana),
		ashe: AsheToJSON(value.ashe),
		baptiste: BaptisteToJSON(value.baptiste),
		bastion: BastionToJSON(value.bastion),
		brigitte: BrigitteToJSON(value.brigitte),
		cassidy: CassidyToJSON(value.cassidy),
		dva: DvaToJSON(value.dva),
		doomfist: DoomfistToJSON(value.doomfist),
		echo: EchoToJSON(value.echo),
		genji: GenjiToJSON(value.genji),
		hanzo: HanzoToJSON(value.hanzo),
		'junker-queen': JunkerQueenToJSON(value.junkerQueen),
		junkrat: JunkratToJSON(value.junkrat),
		kiriko: KirikoToJSON(value.kiriko),
		lifeweaver: LifeweaverToJSON(value.lifeweaver),
		lucio: LucioToJSON(value.lucio),
		mei: MeiToJSON(value.mei),
		mercy: MercyToJSON(value.mercy),
		moira: MoiraToJSON(value.moira),
		orisa: OrisaToJSON(value.orisa),
		pharah: PharahToJSON(value.pharah),
		ramattra: RamattraToJSON(value.ramattra),
		reaper: ReaperToJSON(value.reaper),
		reinhardt: ReinhardtToJSON(value.reinhardt),
		roadhog: RoadhogToJSON(value.roadhog),
		sigma: SigmaToJSON(value.sigma),
		sojourn: SojournToJSON(value.sojourn),
		'soldier-76': Soldier76ToJSON(value.soldier76),
		sombra: SombraToJSON(value.sombra),
		symmetra: SymmetraToJSON(value.symmetra),
		torbjorn: TorbjornToJSON(value.torbjorn),
		tracer: TracerToJSON(value.tracer),
		widowmaker: WidowmakerToJSON(value.widowmaker),
		winston: WinstonToJSON(value.winston),
		'wrecking-ball': WreckingBallToJSON(value.wreckingBall),
		zarya: ZaryaToJSON(value.zarya),
		zenyatta: ZenyattaToJSON(value.zenyatta)
	};
}
