//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * OverFast API
 * OverFast API gives data about Overwatch 2 heroes, gamemodes, maps and players statistics by scraping Blizzard pages. Built with **FastAPI** and **Beautiful Soup**, and uses **nginx** as reverse proxy and **Redis** for caching. By using a Refresh-Ahead cache system, it minimizes calls to Blizzard pages (which can be very slow), and quickly returns accurate data to users.  In players statistics endpoints, several conversions are made for convenience : - all **duration values** are converted into **seconds** (integer) - **percent values** are exposed as **integers** instead of a string with a percent symbol - integer and float string representations are converted into the concerned type  Swagger UI (useful for trying API calls) : https://overfast-api.tekrop.fr/docs
 *
 * The version of the OpenAPI document: 2.17.2
 * Contact: vporchet@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { General } from './General';
import { GeneralFromJSON, GeneralFromJSONTyped, GeneralToJSON } from './General';
import type { Heroes } from './Heroes';
import { HeroesFromJSON, HeroesFromJSONTyped, HeroesToJSON } from './Heroes';
import type { Roles } from './Roles';
import { RolesFromJSON, RolesFromJSONTyped, RolesToJSON } from './Roles';

/**
 *
 * @export
 * @interface PlayerStatsSummary
 */
export interface PlayerStatsSummary {
	/**
	 *
	 * @type {General}
	 * @memberof PlayerStatsSummary
	 */
	general?: General;
	/**
	 *
	 * @type {Roles}
	 * @memberof PlayerStatsSummary
	 */
	roles?: Roles;
	/**
	 *
	 * @type {Heroes}
	 * @memberof PlayerStatsSummary
	 */
	heroes?: Heroes;
}

/**
 * Check if a given object implements the PlayerStatsSummary interface.
 */
export function instanceOfPlayerStatsSummary(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function PlayerStatsSummaryFromJSON(json: any): PlayerStatsSummary {
	return PlayerStatsSummaryFromJSONTyped(json, false);
}

export function PlayerStatsSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerStatsSummary {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		general: !exists(json, 'general') ? undefined : GeneralFromJSON(json['general']),
		roles: !exists(json, 'roles') ? undefined : RolesFromJSON(json['roles']),
		heroes: !exists(json, 'heroes') ? undefined : HeroesFromJSON(json['heroes'])
	};
}

export function PlayerStatsSummaryToJSON(value?: PlayerStatsSummary | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		general: GeneralToJSON(value.general),
		roles: RolesToJSON(value.roles),
		heroes: HeroesToJSON(value.heroes)
	};
}
