//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * OverFast API
 * OverFast API gives data about Overwatch 2 heroes, gamemodes, maps and players statistics by scraping Blizzard pages. Built with **FastAPI** and **Beautiful Soup**, and uses **nginx** as reverse proxy and **Redis** for caching. By using a Refresh-Ahead cache system, it minimizes calls to Blizzard pages (which can be very slow), and quickly returns accurate data to users.  In players statistics endpoints, several conversions are made for convenience : - all **duration values** are converted into **seconds** (integer) - **percent values** are exposed as **integers** instead of a string with a percent symbol - integer and float string representations are converted into the concerned type  Swagger UI (useful for trying API calls) : https://overfast-api.tekrop.fr/docs
 *
 * The version of the OpenAPI document: 2.17.2
 * Contact: vporchet@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Stats } from './Stats';
import { StatsFromJSON, StatsFromJSONTyped, StatsToJSON } from './Stats';
import type { Summary } from './Summary';
import { SummaryFromJSON, SummaryFromJSONTyped, SummaryToJSON } from './Summary';

/**
 *
 * @export
 * @interface Player
 */
export interface Player {
	/**
	 *
	 * @type {Summary}
	 * @memberof Player
	 */
	summary: Summary;
	/**
	 *
	 * @type {Stats}
	 * @memberof Player
	 */
	stats?: Stats;
}

/**
 * Check if a given object implements the Player interface.
 */
export function instanceOfPlayer(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'summary' in value;

	return isInstance;
}

export function PlayerFromJSON(json: any): Player {
	return PlayerFromJSONTyped(json, false);
}

export function PlayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Player {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		summary: SummaryFromJSON(json['summary']),
		stats: !exists(json, 'stats') ? undefined : StatsFromJSON(json['stats'])
	};
}

export function PlayerToJSON(value?: Player | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		summary: SummaryToJSON(value.summary),
		stats: StatsToJSON(value.stats)
	};
}
