//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * OverFast API
 * OverFast API gives data about Overwatch 2 heroes, gamemodes, maps and players statistics by scraping Blizzard pages. Built with **FastAPI** and **Beautiful Soup**, and uses **nginx** as reverse proxy and **Redis** for caching. By using a Refresh-Ahead cache system, it minimizes calls to Blizzard pages (which can be very slow), and quickly returns accurate data to users.  In players statistics endpoints, several conversions are made for convenience : - all **duration values** are converted into **seconds** (integer) - **percent values** are exposed as **integers** instead of a string with a percent symbol - integer and float string representations are converted into the concerned type  Swagger UI (useful for trying API calls) : https://overfast-api.tekrop.fr/docs
 *
 * The version of the OpenAPI document: 2.17.2
 * Contact: vporchet@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CareerStats } from './CareerStats';
import { CareerStatsFromJSON, CareerStatsFromJSONTyped, CareerStatsToJSON } from './CareerStats';
import type { HeroesComparisons } from './HeroesComparisons';
import { HeroesComparisonsFromJSON, HeroesComparisonsFromJSONTyped, HeroesComparisonsToJSON } from './HeroesComparisons';

/**
 * Quickplay statistics about heroes. If the player doesn't have stats for this gamemode, it's null.
 * @export
 * @interface Quickplay
 */
export interface Quickplay {
	/**
	 *
	 * @type {HeroesComparisons}
	 * @memberof Quickplay
	 */
	heroesComparisons: HeroesComparisons;
	/**
	 *
	 * @type {CareerStats}
	 * @memberof Quickplay
	 */
	careerStats: CareerStats;
}

/**
 * Check if a given object implements the Quickplay interface.
 */
export function instanceOfQuickplay(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'heroesComparisons' in value;
	isInstance = isInstance && 'careerStats' in value;

	return isInstance;
}

export function QuickplayFromJSON(json: any): Quickplay {
	return QuickplayFromJSONTyped(json, false);
}

export function QuickplayFromJSONTyped(json: any, ignoreDiscriminator: boolean): Quickplay {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		heroesComparisons: HeroesComparisonsFromJSON(json['heroes_comparisons']),
		careerStats: CareerStatsFromJSON(json['career_stats'])
	};
}

export function QuickplayToJSON(value?: Quickplay | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		heroes_comparisons: HeroesComparisonsToJSON(value.heroesComparisons),
		career_stats: CareerStatsToJSON(value.careerStats)
	};
}
