//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * OverFast API
 * OverFast API gives data about Overwatch 2 heroes, gamemodes, maps and players statistics by scraping Blizzard pages. Built with **FastAPI** and **Beautiful Soup**, and uses **nginx** as reverse proxy and **Redis** for caching. By using a Refresh-Ahead cache system, it minimizes calls to Blizzard pages (which can be very slow), and quickly returns accurate data to users.  In players statistics endpoints, several conversions are made for convenience : - all **duration values** are converted into **seconds** (integer) - **percent values** are exposed as **integers** instead of a string with a percent symbol - integer and float string representations are converted into the concerned type  Swagger UI (useful for trying API calls) : https://overfast-api.tekrop.fr/docs
 *
 * The version of the OpenAPI document: 2.17.2
 * Contact: vporchet@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Role } from './Role';
import { RoleFromJSON, RoleFromJSONTyped, RoleToJSON } from './Role';

/**
 *
 * @export
 * @interface RoleDetail
 */
export interface RoleDetail {
	/**
	 *
	 * @type {Role}
	 * @memberof RoleDetail
	 */
	key: Role;
	/**
	 * Name of the role
	 * @type {string}
	 * @memberof RoleDetail
	 */
	name: string;
	/**
	 * Icon URL of the role
	 * @type {string}
	 * @memberof RoleDetail
	 */
	icon: string;
	/**
	 * Description of the role
	 * @type {string}
	 * @memberof RoleDetail
	 */
	description: string;
}

/**
 * Check if a given object implements the RoleDetail interface.
 */
export function instanceOfRoleDetail(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'key' in value;
	isInstance = isInstance && 'name' in value;
	isInstance = isInstance && 'icon' in value;
	isInstance = isInstance && 'description' in value;

	return isInstance;
}

export function RoleDetailFromJSON(json: any): RoleDetail {
	return RoleDetailFromJSONTyped(json, false);
}

export function RoleDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleDetail {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		key: RoleFromJSON(json['key']),
		name: json['name'],
		icon: json['icon'],
		description: json['description']
	};
}

export function RoleDetailToJSON(value?: RoleDetail | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		key: RoleToJSON(value.key),
		name: value.name,
		icon: value.icon,
		description: value.description
	};
}
