//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * OverFast API
 * OverFast API gives data about Overwatch 2 heroes, gamemodes, maps and players statistics by scraping Blizzard pages. Built with **FastAPI** and **Beautiful Soup**, and uses **nginx** as reverse proxy and **Redis** for caching. By using a Refresh-Ahead cache system, it minimizes calls to Blizzard pages (which can be very slow), and quickly returns accurate data to users.  In players statistics endpoints, several conversions are made for convenience : - all **duration values** are converted into **seconds** (integer) - **percent values** are exposed as **integers** instead of a string with a percent symbol - integer and float string representations are converted into the concerned type  Swagger UI (useful for trying API calls) : https://overfast-api.tekrop.fr/docs
 *
 * The version of the OpenAPI document: 2.17.2
 * Contact: vporchet@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface StoryChapter
 */
export interface StoryChapter {
	/**
	 * Title of the chapter
	 * @type {string}
	 * @memberof StoryChapter
	 */
	title: string;
	/**
	 * Content of the chapter
	 * @type {string}
	 * @memberof StoryChapter
	 */
	content: string;
	/**
	 * URL of the picture illustrating the chapter
	 * @type {string}
	 * @memberof StoryChapter
	 */
	picture: string;
}

/**
 * Check if a given object implements the StoryChapter interface.
 */
export function instanceOfStoryChapter(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'title' in value;
	isInstance = isInstance && 'content' in value;
	isInstance = isInstance && 'picture' in value;

	return isInstance;
}

export function StoryChapterFromJSON(json: any): StoryChapter {
	return StoryChapterFromJSONTyped(json, false);
}

export function StoryChapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryChapter {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		title: json['title'],
		content: json['content'],
		picture: json['picture']
	};
}

export function StoryChapterToJSON(value?: StoryChapter | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		title: value.title,
		content: value.content,
		picture: value.picture
	};
}
