//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * OverFast API
 * OverFast API gives data about Overwatch 2 heroes, gamemodes, maps and players statistics by scraping Blizzard pages. Built with **FastAPI** and **Beautiful Soup**, and uses **nginx** as reverse proxy and **Redis** for caching. By using a Refresh-Ahead cache system, it minimizes calls to Blizzard pages (which can be very slow), and quickly returns accurate data to users.  In players statistics endpoints, several conversions are made for convenience : - all **duration values** are converted into **seconds** (integer) - **percent values** are exposed as **integers** instead of a string with a percent symbol - integer and float string representations are converted into the concerned type  Swagger UI (useful for trying API calls) : https://overfast-api.tekrop.fr/docs
 *
 * The version of the OpenAPI document: 2.17.2
 * Contact: vporchet@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Total values for generic stats : eliminations, assists, deaths, damage, healing
 * @export
 * @interface Total
 */
export interface Total {
	/**
	 * Total number of eliminations
	 * @type {number}
	 * @memberof Total
	 */
	eliminations: number;
	/**
	 * Total number of assists
	 * @type {number}
	 * @memberof Total
	 */
	assists: number;
	/**
	 * Total number of deaths
	 * @type {number}
	 * @memberof Total
	 */
	deaths: number;
	/**
	 * Total damage done
	 * @type {number}
	 * @memberof Total
	 */
	damage: number;
	/**
	 * Total healing done
	 * @type {number}
	 * @memberof Total
	 */
	healing: number;
}

/**
 * Check if a given object implements the Total interface.
 */
export function instanceOfTotal(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'eliminations' in value;
	isInstance = isInstance && 'assists' in value;
	isInstance = isInstance && 'deaths' in value;
	isInstance = isInstance && 'damage' in value;
	isInstance = isInstance && 'healing' in value;

	return isInstance;
}

export function TotalFromJSON(json: any): Total {
	return TotalFromJSONTyped(json, false);
}

export function TotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Total {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		eliminations: json['eliminations'],
		assists: json['assists'],
		deaths: json['deaths'],
		damage: json['damage'],
		healing: json['healing']
	};
}

export function TotalToJSON(value?: Total | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		eliminations: value.eliminations,
		assists: value.assists,
		deaths: value.deaths,
		damage: value.damage,
		healing: value.healing
	};
}
