//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * OverFast API
 * OverFast API gives data about Overwatch 2 heroes, gamemodes, maps and players statistics by scraping Blizzard pages. Built with **FastAPI** and **Beautiful Soup**, and uses **nginx** as reverse proxy and **Redis** for caching. By using a Refresh-Ahead cache system, it minimizes calls to Blizzard pages (which can be very slow), and quickly returns accurate data to users.  In players statistics endpoints, several conversions are made for convenience : - all **duration values** are converted into **seconds** (integer) - **percent values** are exposed as **integers** instead of a string with a percent symbol - integer and float string representations are converted into the concerned type  Swagger UI (useful for trying API calls) : https://overfast-api.tekrop.fr/docs
 *
 * The version of the OpenAPI document: 2.17.2
 * Contact: vporchet@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocationInner } from './LocationInner';
import { LocationInnerFromJSON, LocationInnerFromJSONTyped, LocationInnerToJSON } from './LocationInner';

/**
 *
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
	/**
	 *
	 * @type {Array<LocationInner>}
	 * @memberof ValidationError
	 */
	loc: Array<LocationInner>;
	/**
	 *
	 * @type {string}
	 * @memberof ValidationError
	 */
	msg: string;
	/**
	 *
	 * @type {string}
	 * @memberof ValidationError
	 */
	type: string;
}

/**
 * Check if a given object implements the ValidationError interface.
 */
export function instanceOfValidationError(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'loc' in value;
	isInstance = isInstance && 'msg' in value;
	isInstance = isInstance && 'type' in value;

	return isInstance;
}

export function ValidationErrorFromJSON(json: any): ValidationError {
	return ValidationErrorFromJSONTyped(json, false);
}

export function ValidationErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationError {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		loc: (json['loc'] as Array<any>).map(LocationInnerFromJSON),
		msg: json['msg'],
		type: json['type']
	};
}

export function ValidationErrorToJSON(value?: ValidationError | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		loc: (value.loc as Array<any>).map(LocationInnerToJSON),
		msg: value.msg,
		type: value.type
	};
}
