//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * OverFast API
 * OverFast API gives data about Overwatch 2 heroes, gamemodes, maps and players statistics by scraping Blizzard pages. Built with **FastAPI** and **Beautiful Soup**, and uses **nginx** as reverse proxy and **Redis** for caching. By using a Refresh-Ahead cache system, it minimizes calls to Blizzard pages (which can be very slow), and quickly returns accurate data to users.  In players statistics endpoints, several conversions are made for convenience : - all **duration values** are converted into **seconds** (integer) - **percent values** are exposed as **integers** instead of a string with a percent symbol - integer and float string representations are converted into the concerned type  Swagger UI (useful for trying API calls) : https://overfast-api.tekrop.fr/docs
 *
 * The version of the OpenAPI document: 2.17.2
 * Contact: vporchet@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Link } from './Link';
import { LinkFromJSON, LinkFromJSONTyped, LinkToJSON } from './Link';

/**
 * Video of the ability
 * @export
 * @interface Video
 */
export interface Video {
	/**
	 * Thumbnail of the ability video
	 * @type {string}
	 * @memberof Video
	 */
	thumbnail: string;
	/**
	 *
	 * @type {Link}
	 * @memberof Video
	 */
	link: Link;
}

/**
 * Check if a given object implements the Video interface.
 */
export function instanceOfVideo(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'thumbnail' in value;
	isInstance = isInstance && 'link' in value;

	return isInstance;
}

export function VideoFromJSON(json: any): Video {
	return VideoFromJSONTyped(json, false);
}

export function VideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Video {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		thumbnail: json['thumbnail'],
		link: LinkFromJSON(json['link'])
	};
}

export function VideoToJSON(value?: Video | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		thumbnail: value.thumbnail,
		link: LinkToJSON(value.link)
	};
}
